import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const { address, lat, lng, zoom, heading, tilt, image, prompt: userPrompt } = await request.json();

    const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
    const geminiApiKey = process.env.GEMINI_API_KEY;

    if (!apiKey || !geminiApiKey) {
      return NextResponse.json(
        { error: "Missing API keys" },
        { status: 500 }
      );
    }

    let inputImageBase64 = image;

    // 1. If no image provided, fetch Static Map
    if (!inputImageBase64) {
      // Note: Static Maps API doesn't support heading/tilt for satellite maps
      // We use a larger size to ensure good quality for the AI
      const staticMapUrl = `https://maps.googleapis.com/maps/api/staticmap?center=${lat},${lng}&zoom=${zoom}&size=640x640&maptype=satellite&key=${apiKey}`;

      console.log("Fetching static map from:", staticMapUrl);
      const mapResponse = await fetch(staticMapUrl);
      
      if (!mapResponse.ok) {
        const errorText = await mapResponse.text();
        console.error("Failed to fetch static map:", mapResponse.statusText, errorText);
        return NextResponse.json(
          { error: "Failed to capture map view", details: `${mapResponse.statusText}: ${errorText}` },
          { status: 500 }
        );
      }

      const mapBuffer = await mapResponse.arrayBuffer();
      inputImageBase64 = Buffer.from(mapBuffer).toString("base64");
    } else {
        // If image is provided as data URL, strip the prefix
        if (inputImageBase64.startsWith("data:image")) {
            inputImageBase64 = inputImageBase64.split(",")[1];
        }
    }

    // 2. Call Gemini 3 Pro Image Preview
    const ai = new GoogleGenAI({ apiKey: geminiApiKey });

    const defaultPrompt = `
      Generate a professional architectural site plan based on this satellite image of ${address}.
      
      Requirements:
      1. Create a top-down, scaled site plan.
      2. Clearly define property boundaries, buildings, driveways, and pathways.
      3. Use a professional architectural style (clean lines, blueprint or rendered style).
      4. Include landscaping elements like trees and gardens where appropriate based on the image.
      5. Maintain the orientation and scale of the original image.
      6. The output should be a high-quality image suitable for presentation.
    `;

    const finalPrompt = userPrompt || defaultPrompt;

    console.log("Calling Gemini 3 Pro...");
    const response = await ai.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: [
        { text: finalPrompt },
        {
          inlineData: {
            mimeType: "image/png",
            data: inputImageBase64,
          },
        },
      ],
      config: {
        responseModalities: ["TEXT", "IMAGE"],
      },
    });

    // 3. Extract and return the generated image
    let generatedImageBase64 = null;
    let generatedText = "";

    // The response structure might vary slightly based on the SDK version/model, 
    // but typically it's in candidates[0].content.parts
    const candidate = response.candidates?.[0];
    if (candidate?.content?.parts) {
      for (const part of candidate.content.parts) {
        if (part.text) {
          generatedText += part.text;
        } else if (part.inlineData) {
          generatedImageBase64 = part.inlineData.data;
        }
      }
    }

    if (!generatedImageBase64) {
      console.error("No image generated by Gemini:", generatedText);
      return NextResponse.json(
        { error: "Failed to generate site plan image", details: generatedText },
        { status: 500 }
      );
    }

    // Return the image as a data URL
    const dataUrl = `data:image/png;base64,${generatedImageBase64}`;

    return NextResponse.json({ 
      image: dataUrl,
      text: generatedText 
    });

  } catch (error) {
    console.error("Error generating plan:", error);
    return NextResponse.json(
      { error: "Internal server error", details: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    );
  }
}
